### ISSUE TITLE
Invalid column when upgrading

### ISSUE THREAD

**Issue by JoshuaFolkerts** [andrewmarkham/contentsecuritypolicy#101]
Upgraded new version of the Security item and the following error occurs.
`2024-08-08T01:07:46.9403819Z	The property ReportingMode exists on both the old and new definitions but does not have the same type and converting a value caused an exception in the provider.
2024-08-08T01:07:46.9403917Z	Invalid column name 'ReportingMode'.
2024-08-08T01:07:46.940403Z	Invalid column name 'ReportingMode'.
2024-08-08T01:07:46.9404119Z	   at EPiServer.Data.Dynamic.StoreDefinition.TryMoveDataToUpdatingProperties(List`1 updatingProperties, IList`1 newMappings, StoreDefinitionParameters parameters, Boolean moveDataForRenamedProperties)
2024-08-08T01:07:46.9404226Z	   at EPiServer.Data.Dynamic.StoreDefinition.Remap(IDictionary`2 typeBag, StoreDefinitionParameters parameters)
2024-08-08T01:07:46.9404314Z	   at EPiServer.Data.Dynamic.StoreDefinition.Remap(Type type)
2024-08-08T01:07:46.9404413Z	   at Jhoose.Security.Repository.StandardCspPolicyRepository.Remap[T]()
2024-08-08T01:07:46.940449Z	   at Jhoose.Security.Repository.StandardCspPolicyRepository.Bootstrap()
2024-08-08T01:07:46.9404567Z	   at Jhoose.Security.Core.Provider.StandardCspProvider.Initialize()
2024-08-08T01:07:46.9404665Z	   at Jhoose.Security.DependencyInjection.InitialiseHostedService.<StartAsync>b__2_0()`

Not sure where this would be coming from

**Comment by andrewmarkham** [comment]
Hi @JoshuaFolkerts,

Can you let me know which version you are upgrading from and I will take a look.

Thanks

**Comment by JoshuaFolkerts** [comment]
Good day.  I was on version 2.2.2.267 and upgraded to the latest version of 2.3.0.285.   I hope that helps

**Comment by andrewmarkham** [comment]
I have noticed an error, can you add the following
            services.AddJhooseSecurityCoreReporting();
and
            app.UseJhooseSecurityReporting();

and let me know if this resolves the issue.  I will sort out a bug fix so that's there no need to do this.

**Comment by andrewmarkham** [comment]
Hi, I have just released a new version 2.3.1, this removes the requirement to add the reporting as per my previous comment, can you let me know if this resolves the error message.
Thanks

**Comment by andrewmarkham** [comment]
Hi @JoshuaFolkerts, are you still seeing this issue?

**Comment by JoshuaFolkerts** [comment]
The reporting seems to be fixed but what actually didn't get fixed was the upgrade to the newer version where it seems like it tries to remap a content type in DDS to another type and that is failing on me with the same error message.  Sorry, was out this weekend

**Comment by andrewmarkham** [comment]
That's a bit weird, as it's actually a new property created in this release.  Is this an error that's being output in the logs at startup?  Can you set the reporting mode okay?  This is in the settings.

**Comment by JoshuaFolkerts** [comment]
System.InvalidOperationException: '
The property ReportingMode exists on both the old and new definitions but does not have the same type and converting a value caused an exception in the provider.
Invalid column name 'ReportingMode'.
Invalid column name 'ReportingMode'.'
I just ran it and get this in the console

**Comment by JoshuaFolkerts** [comment]
Here is the full error if it helps
`2024-08-15T23:42:26.371120803Z Unhandled exception. System.InvalidOperationException: 
2024-08-15T23:42:26.371147203Z The property ReportingMode exists on both the old and new definitions but does not have the same type and converting a value caused an exception in the provider.
2024-08-15T23:42:26.371192004Z Invalid column name 'ReportingMode'.
2024-08-15T23:42:26.371285105Z Invalid column name 'ReportingMode'.
2024-08-15T23:42:26.371294905Z    at EPiServer.Data.Dynamic.StoreDefinition.TryMoveDataToUpdatingProperties(List`1 updatingProperties, IList`1 newMappings, StoreDefinitionParameters parameters, Boolean moveDataForRenamedProperties)
2024-08-15T23:42:26.371299505Z    at EPiServer.Data.Dynamic.StoreDefinition.Remap(IDictionary`2 typeBag, StoreDefinitionParameters parameters)
2024-08-15T23:42:26.371303406Z    at EPiServer.Data.Dynamic.StoreDefinition.Remap(Type type)
2024-08-15T23:42:26.371307206Z    at Jhoose.Security.Repository.StandardCspPolicyRepository.Remap[T]()
2024-08-15T23:42:26.371310806Z    at Jhoose.Security.Repository.StandardCspPolicyRepository.Bootstrap()
2024-08-15T23:42:26.371314206Z    at Jhoose.Security.Core.Provider.StandardCspProvider.Initialize()
2024-08-15T23:42:26.371318006Z    at Jhoose.Security.DependencyInjection.InitialiseHostedService.<StartAsync>b__2_0()
2024-08-15T23:42:26.371322206Z    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2024-08-15T23:42:26.371326106Z --- End of stack trace from previous location ---
2024-08-15T23:42:26.371329706Z    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2024-08-15T23:42:26.371333606Z    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2024-08-15T23:42:26.371337306Z --- End of stack trace from previous location ---
2024-08-15T23:42:26.371341006Z    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
2024-08-15T23:42:26.371345006Z    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
2024-08-15T23:42:26.371349106Z    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2024-08-15T23:42:26.371352906Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2024-08-15T23:42:26.371360206Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2024-08-15T23:42:26.371364106Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2024-08-15T23:42:26.371367907Z    at Opti.Program.Main(String[] args) in /home/vsts/work/1/s/src/Program.cs:line 9`

**Comment by andrewmarkham** [comment]
Hi @JoshuaFolkerts 

Can you run the following scripts and send the results back to me as a CSV/Excel file?

SELECT *
FROM tblBigTable
WHERE StoreName Like 'Jhoose%'

SELECT *
FROM [tblBigTableStoreInfo]
WHERE PropertyName = 'ReportingMode'

Is this stopping the site from starting, or is it just throwing an error?

Thanks

**Comment by kennygutierrez-century** [comment]
We've had this same issue. We had to downgrade. Is there a fix in the works?

**Comment by andrewmarkham** [comment]
Hi @kennygutierrez-century I am unable to reproduce the issue.

Can you run the SQL scripts shown above and send me the results?  This should help me work out what the problem is.

**Comment by andrewmarkham** [comment]
Hi @JoshuaFolkerts / @kennygutierrez-century 

Can you provide anymore information, I would like to understand this issue some more.

Thanks

**Comment by kennygutierrez-century** [comment]
Hi @andrewmarkham I provided the query results in the Optimizely Slack.

**Comment by andrewmarkham** [comment]
Hi @kennygutierrez-century / @JoshuaFolkerts 

I have just released a new version, and I am hoping it resolves the issue.  I am still unable to reproduce locally.

Please install V2.4.0 once it is available on the nuget feed and let me know if this resolves the issue for you.

Andy

**Comment by andrewmarkham** [comment]
@kennygutierrez-century you are correct about the top menu.  It's not something that I have noticed before.  I will create a separate ticket for this.

**Comment by andrewmarkham** [comment]
@JoshuaFolkerts - I am going to close this issue, please let me know if you are still facing an issue with the latest version.

**Comment by andrewmarkham** [comment]
Hi @JoshuaFolkerts 

I have had another occurrence of this issue.  It isn't clear what the root cause of the problem is, but looking at the database it seems that the properytype has not been set correctly.   It's being recorded as an int rather than the ENUM.

This script should fix the issue

UPDATE tblBigTableStoreInfo
 set PropertyType = 'Jhoose.Security.Core.Models.CSP.ReportingMode, Jhoose.Security.Core, Version=2.4.0.328, Culture=neutral, PublicKeyToken=null'
WHERE PropertyName = 'ReportingMode'

Please try running this script, but backup your database first :)

Thanks

**Comment by JoshuaFolkerts** [comment]
Ill give it a whirl and see what happens here.  Thanks Andrew
