### ISSUE TITLE
 Server cannot append header after HTTP headers have been sent.

### ISSUE THREAD

**Issue by mrthilton** [andrewmarkham/contentsecuritypolicy#36]
HI Andrew, 

I have installed this, must say really like this :)

I am getting an error logged, I wonder if you have seen it previously.

```
2022-06-16T14:20:10,Error,,3aa17f,637909860100312142,0,1060,90,"EPiServer.Global : Unhandled exception in ASP.NET
System.Web.HttpException (0x80004005): Server cannot append header after HTTP headers have been sent.
   at System.Web.HttpHeaderCollection.SetHeader(String name, String value, Boolean replace)
   at Jhoose.Security.Services.JhooseSecurityService.AddContentSecurityPolicy(HttpResponse response)
   at Jhoose.Security.HttpModules.JhooseSecurityModule.Context_EndRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.<>c__DisplayClass285_0.b__0()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)",
```

V1.2.2 Epi 11

Tim H

**Comment by andrewmarkham** [comment]
Tim,

I have fixed this issue, and uploaded a new version of the nuget package.  This should become avaliable sometime today.
